server:
  port: 8080

spring:
  application:
    name: rag-backend
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB
  jackson:
    time-zone: Asia/Seoul

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
